### ISSUE TITLE
/metadata endpoint should properly quote variables for shell env

### ISSUE THREAD

**Issue by rothgar** [poseidon/matchbox#202] opened 2016-05-13 17:02 UTC
If I download the metadata file for a host from bootcfg I get the key values as expected but some values are not formatted properly for injection into the shell.

e.g.
`SSH_AUTHORIZED_KEYS=[ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpGinBIqbhSm0...]`

Is not properly sourced and cannot be used in the shell. It also will echo everything after the space and throw an error `: No such file or directory`

I'm not sure how these are expected to be used but I use them in my systemd unit files for environment variables. With that I would expect them to be quoted and formatted to be used as an array.

e.g.

```
SSH_AUTHORIZED_KEYS=("ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpGinBIqbhSm0...", \
    "ssh-rsa SOMEOTHERKEY...")
```

Any further parsing of the variables can be done with awk with something like `echo $SSH_AUTHORIZED_KEYS[0] | awk '{print $2}'`

**Comment by dghubble** [comment] 2016-05-13 18:17
> I'm not sure how these are expected to be used

The `/metadata` endpoint simply provides the metadata for the group that was matched for any edge cases that aren't already covered by templating Ignition files (or cloud-config). It also demonstrates an endpoint that can be used to provide dynamic metadata (fetched on each boot) for systemd unit environment variables if required. However, if you look through the examples, `/metadata` is not used for any of the reference clusters.

> I use them in my systemd unit files for environment variables.

You might favor templating values into your Ignition/Cloud-config units unless you have specific parts which need data fetched from a `bootcfg` service on each boot. Using the raw result or the result dumped to a file (like this [metadata.service](https://github.com/coreos/coreos-baremetal/blob/4e563bbce3e0130c466feee322ac1d4e29ddb294/examples/ignition/etcd-proxy.yaml#L5)) is probably only ok for simple use cases. AWS [EC2 metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) provides a path per value and other tools are written to parse that tree for useful purposes. We might follow those conventions to develop the endpoint in future.

**Comment by BugRoger** [comment] 2016-06-09 08:12
For what it's worth we ran into the same problem. We curled the metadata down and reused it in our scripts. It's ok for us to have a separate template for it.

**Comment by urzds** [comment] 2016-08-04 18:30
Duplicate of #84 and #85?

**Comment by dghubble** [comment] 2016-08-04 18:40
The `/metadata` endpoint doesn't include lists in a way that can be sourced in a shell script as @rothgar asked. Lists are ignored. If a particular representation of the list is needed, one option is to use a generic template (can be any Go template). https://github.com/coreos/coreos-baremetal/blob/master/Documentation/api.md#generic-config

From PR https://github.com/coreos/coreos-baremetal/pull/279:

A request /metadata?mac=52-54-00-a1-9c-ae&foo=bar&count=3&gate=true which matches a group definition:

```
{
  "id": "some-id",
  "name": "some-name",
  "profile": "some-profile",
  "selector": {
    "mac": "52:54:00:a1:9c:ae"
  },
  "metadata": {
    "meta": "data",
    "etcd": {
      "name": "node1"
    },
    "some": {
      "nested": {
        "data": "some-value"
      }
    }
  }
}
```

includes group metadata, selectors and the request-scoped query params and "raw_query" in an "env-file" style /metadata response which can be used for various purposes.

```
META=data
ETCD_NAME=node1
SOME_NESTED_DATA=some-value
MAC=52:54:00:a1:9c:ae
REQUEST_QUERY_MAC=52:54:00:a1:9c:ae
REQUEST_QUERY_FOO=bar
REQUEST_QUERY_COUNT=3
REQUEST_QUERY_GATE=true
REQUEST_RAW_QUERY=mac=52-54-00-a1-9c-ae&foo=bar&count=3&gate=true
```

Lists are ignored.

**Closed** 2019-12-03 05:30 UTC
Labels: priority/Pmaybe
